apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: course-service
  template:
    metadata:
      labels:
        app: course-service
    spec:
      containers:
        - name: course-service
          image: course-service:v1
          ports:
            - containerPort: 3003